### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by palansuya** [shanzhenren/ClusType#1]
I ran ClusType on the yelp corpus that was provided but somehow it failed and provided me with this message. 

> # links in S_L: 141185 , #links in S_R: 168899
> 
> S_M dims 277337 277337 #links in S_M: 1685222
> graph loading DONE
> No target type entity seeded!!!!
> Percent Seeded Mention: 0.0 % of 277337 , #target/All =
> Traceback (most recent call last):
>   File "src/step1-entity_recognition.py", line 80, in <module>
>     Y0 = set_Y(seed_mid, seedMention_tid_score, mid_mention, m, T).todense()
>   File "/Text_Mining/Method/shanzhenren-ClusType-3669a07/shanzhenren-ClusType-3669a07/src/algorithm.py", line 66, in set_Y
>     ', #target/All = ', num_target/(Y.nnz) \* 100
> ZeroDivisionError: integer division or modulo by zero

Do you know what might have happened?

**Comment by shanzhenren** [comment]
Dear Palansuya,

This is probably because the entity linking module fails (did you check the linker API?) and leads to no seed entity.

Regards,
Xiang Ren

**Comment by shanzhenren** [comment]
Dear Palansuya,

We update the entity linking module and also the run.sh. The current version should be able to generate correct linking results.

**Comment by abisee** [comment]
I just ran on the Yelp corpus and had the same result. I cloned the repo last week.

**Comment by shanzhenren** [comment]
@palansuya @abisee , this is probably due to the temporary failure of [DBpediaSpotlight API](https://github.com/dbpedia-spotlight/dbpedia-spotlight) used in our entity linking module (`entity_linking/EntityLinking.py`). I include the links to download corresponding linking results (https://www.dropbox.com/s/w628rwpb3kbmuea/seed_yelp.txt?dl=0) in README. For Yelp, you can download from [here](), and put it under `data/yelp/` directory.
